#!/usr/bin/env python3
"""Teacher fidelity by input length on the 5,000 held-out pages (heldout5k), release decoding.
Table 8 (tab:fidelity-by-length) is the "main_text" convention of the output (--tex writes the tabular).

Same definitions as the earlier 960-page version of this table (heldout960 = first 960 pages):
  * input length  = number of regex word tokens (\\w+) of the page's model input, i.e. the numbered
                    rendering *including* its "<lid:N>" line markers (this reproduces the 960 table's
                    quartile bounds 100/684/684/1103/1104/1762/1762/11618 exactly on the first 960 pages);
  * quartiles     = four equal-count buckets after sorting by input length;
  * decision acc. = teacher tag == executor tag (4 classes);
  * token P/R/F1  = corpus-level (pooled over the bucket) overlap of lower-cased \\w+ token multisets of the
                    student's corpus text vs the teacher's, deleted pages = "".
Inputs (page-aligned by gid; written by evaluation/):
  $WORK_DIR/eval/heldout5k/heldout5k.jsonl
      teacher tag / gfinal (teacher text = body_from_prediction_dfirst(input, output))
  $WORK_DIR/eval/heldout_pipeline/work/heldout5k_rel/ours.jsonl
      release outputs (T=1, top_p=1, 3,072-token cap; full arm of the operation ablation),
      status "ok" | "skip:too_long" (11 pages never sent to the model)
Three page-set conventions are written (the 960 prefix has no skipped and no over-context pages, so all three
coincide there):
  main_text   pages sent to the model (4,989); token scores only on pages whose teacher target fits the
              32,768-token context (plen + tlen <= 32768; 4,986) -- the teacher-fidelity convention of the
              held-out pipeline, behind the main text's F1 89.3
  script960   pages sent to the model (4,989); token scores on all of them (convention of the 960-page table)
  all5000     all 5,000 pages; skipped pages count as <delete> with empty text (the Sankey convention)
Quartiles are always formed over the page set of the convention.
usage: analyze_fidelity_by_length_5k.py [--out $FIG_DATA_DIR/fidelity_by_length_5k.json] [--tex <stem>]
"""

import argparse
import json
import os
import re
import sys
from collections import Counter
from pathlib import Path

HERE = Path(__file__).resolve().parent  # analysis/
DATA_DIR = Path(os.environ.get("FIG_DATA_DIR", HERE / "data"))
WORK_DIR = os.environ.get("WORK_DIR", "")  # see configs/paths.env.example
GOLD = Path(WORK_DIR) / "eval" / "heldout5k" / "heldout5k.jsonl"
OURS = Path(WORK_DIR) / "eval" / "heldout_pipeline" / "work" / "heldout5k_rel" / "ours.jsonl"
TOK = re.compile(r"\w+")
MAXLEN = 32768
TAG = {"keep": "<extract>", "edit": "<refine>", "delete": "<delete>", "rewrite": "<rewrite>"}


def load(path):
    return [json.loads(line) for line in path.open(encoding="utf-8") if line.strip()]


def score(subset):
    """subset: list of dicts with length, gt, pt, gfinal, pfinal, tok (bool: include in token scores)."""
    acc = sum(r["gt"] == r["pt"] for r in subset) / len(subset)
    enters = sum((r["gt"] == "<delete>") == (r["pt"] == "<delete>") for r in subset) / len(subset)
    overlap = student_total = teacher_total = 0
    for r in subset:
        if not r["tok"]:
            continue
        student = Counter(TOK.findall(r["pfinal"].lower()))
        teacher = Counter(TOK.findall(r["gfinal"].lower()))
        overlap += sum((student & teacher).values())
        student_total += sum(student.values())
        teacher_total += sum(teacher.values())
    precision = overlap / student_total if student_total else 1.0
    recall = overlap / teacher_total if teacher_total else 1.0
    f1 = 2 * precision * recall / (precision + recall) if precision + recall else 0.0
    return {
        "pages": len(subset),
        "pages_token_scored": sum(r["tok"] for r in subset),
        "min_input_tokens": min(r["length"] for r in subset),
        "max_input_tokens": max(r["length"] for r in subset),
        "decision_accuracy": acc,
        "enters_corpus_agreement": enters,
        "text_token_precision": precision,
        "text_token_recall": recall,
        "text_token_f1": f1,
    }


def table(rows):
    rows = sorted(rows, key=lambda r: r["length"])  # stable, like the 960 script
    out = {"pages": len(rows), "buckets": []}
    for q in range(4):
        lo, hi = q * len(rows) // 4, (q + 1) * len(rows) // 4
        out["buckets"].append({"quartile": q + 1, **score(rows[lo:hi])})
    out["all"] = score(rows)
    return out


def tex(result, conv):
    t = result["conventions"][conv]
    f = lambda x: "%.2f" % (100 * x)
    n = lambda x: "{:,}".format(x)
    lines = [
        "%% Generated by analysis/analyze_fidelity_by_length_5k.py (convention: %s) -> fidelity_by_length_5k.json" % conv,
        "\\begin{tabular}{lrrrrr}",
        "  \\toprule",
        "  \\textbf{Quartile} & \\textbf{Input tokens} & \\textbf{Decision acc.} & \\textbf{Token P} &",
        "    \\textbf{Token R} & \\textbf{Token F1} \\\\",
        "  \\midrule",
    ]
    for b in t["buckets"]:
        lines.append("  %d & %s--%s & %s & %s & %s & %s \\\\" % (
            b["quartile"], n(b["min_input_tokens"]), n(b["max_input_tokens"]), f(b["decision_accuracy"]),
            f(b["text_token_precision"]), f(b["text_token_recall"]), f(b["text_token_f1"])))
    a = t["all"]
    lines += ["  \\midrule",
              "  All & %s--%s & %s & %s & %s & %s \\\\" % (
                  n(a["min_input_tokens"]), n(a["max_input_tokens"]), f(a["decision_accuracy"]),
                  f(a["text_token_precision"]), f(a["text_token_recall"]), f(a["text_token_f1"])),
              "  \\bottomrule", "\\end{tabular}"]
    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", type=Path, default=DATA_DIR / "fidelity_by_length_5k.json")
    ap.add_argument("--tex", type=Path, default=None, help="write LaTeX tabulars (one per convention) with this stem")
    args = ap.parse_args()
    if not WORK_DIR:
        sys.exit("set WORK_DIR (see configs/paths.env.example)")
    pages, ours = load(GOLD), load(OURS)
    assert [p["gid"] for p in pages] == list(range(len(pages))) == [o["gid"] for o in ours]
    base = []
    for p, o in zip(pages, ours):
        gt = TAG[p["tag"]]
        sent = o["status"] == "ok"
        pt = o["pt"] if sent else "<delete>"
        base.append({
            "gid": p["gid"], "length": len(TOK.findall(p["input"])), "gt": gt, "pt": pt, "sent": sent,
            "fits": sent and o["plen"] + o["tlen"] <= MAXLEN,
            "gfinal": "" if gt == "<delete>" else (p["gfinal"] or ""),
            "pfinal": "" if pt == "<delete>" else (o["text"] or ""),
        })
    conv = {
        "main_text": [dict(r, tok=r["fits"]) for r in base if r["sent"]],
        "script960": [dict(r, tok=True) for r in base if r["sent"]],
        "all5000": [dict(r, tok=True) for r in base],
    }
    result = {
        "description": "Teacher fidelity of the released ReScraper (release decoding: T=1.0, top_p=1.0, max_tokens=3072) on "
                       "the 5,000 held-out pages (heldout5k), in four equal-count quartiles by input length. Input length = "
                       "regex \\w+ tokens of the numbered model input incl. <lid:N> markers (as in the 960-page table). "
                       "Decision accuracy over 4 operations; token P/R/F1 = pooled \\w+ multiset overlap of the text each "
                       "page contributes (deleted -> empty string) with the teacher's.",
        "source": "%s x %s" % (GOLD, OURS),
        "length_unit": "regex word tokens of the <lid:N>-numbered input",
        "skipped_not_sent": [r["gid"] for r in base if not r["sent"]],
        "sent_but_teacher_target_over_context": [r["gid"] for r in base if r["sent"] and not r["fits"]],
        "conventions": {k: table(v) for k, v in conv.items()},
        "convention_notes": {
            "main_text": "pages sent to the model (4,989); token scores exclude pages whose teacher target does not fit the "
                         "32,768-token context; = the held-out pipeline's teacher-fidelity validation (vs_teacher_all)",
            "script960": "pages sent to the model; token scores on all of them (convention of the 960-page table)",
            "all5000": "all 5,000 pages; the 11 pages the release run skipped (prompt too long) count as <delete> / empty",
        },
        "first960_check": {k: score([r for r in v if r["gid"] < 960]) for k, v in conv.items()},
    }
    args.out.write_text(json.dumps(result, indent=2) + "\n", encoding="utf-8")
    for k in conv:
        a = result["conventions"][k]["all"]
        print("%-10s n=%d tok_n=%d acc=%.2f enters=%.2f P=%.2f R=%.2f F1=%.2f" % (
            k, a["pages"], a["pages_token_scored"], 100 * a["decision_accuracy"], 100 * a["enters_corpus_agreement"],
            100 * a["text_token_precision"], 100 * a["text_token_recall"], 100 * a["text_token_f1"]))
        for b in result["conventions"][k]["buckets"]:
            print("   Q%d %6d-%6d n=%d acc=%.2f P=%.2f R=%.2f F1=%.2f" % (
                b["quartile"], b["min_input_tokens"], b["max_input_tokens"], b["pages"], 100 * b["decision_accuracy"],
                100 * b["text_token_precision"], 100 * b["text_token_recall"], 100 * b["text_token_f1"]))
    if args.tex:
        for k in conv:
            Path(str(args.tex) + "_" + k + ".tex").write_text(tex(result, k), encoding="utf-8")
    print("wrote", args.out)


if __name__ == "__main__":
    sys.exit(main())
